
module.exports = {
    STORE_KEY: 'a56z0fzrNpl^2',
    screen :'',
    time : 0,
    BASE_URL: 'http://pumpfit.in/admin/webservices/',
    //BASE_URL: 'http://www.thenewsmen.co.in/newsmentest/admin/api/',
    home :'HomeScreen',
    Signin :'SigninScreen',
    Signup :'SignupScreen',
    guid:'',
    muid:'',
    youtubekey:'AIzaSyCkk0Mc6Hha2LUn3NHubv0LLSiumoPVhWs',
    is_yt:0,
    newsWhich:'',
    userID2:'',
    getPack:'',
    newsImage:'',
    newsTitle:'',
    front_main :'front_main',
    industry :'',
    categoryID : '',
    array :[],
    description:'',
    parts:'',
    needs:'',
    weeks:'',
    week:'',
    workid:'',
    workname:'',
    workimage:'',
    workvideo:'',
    worklevel:'',
    workgrp:'',
    workequip:'',
    workname2:'',
    worktime:'',
    package_id:'',
    packageall:'',
    maintitle:'',
    libcat:'',
    userdet:'',
    userpro:'',
    userID:'',
    profilepic:'',
    profile :'',
    token: '',
    event_id:'',
    productname : '',
    username: '',
    gender: '',
    email: '',
    image:'',
    password: '',
    dob: '',
    related:'',
    productid: '',
    cartId :'',
    myid :'',
    video:'',
    newsid :'',
    derive_category :'derive_category',
    derive_detail_category : 'derive_detail_category',
    info_number :'',
    info_email : '',
    mainid : '',
    user_id:'',
    dervie_detail_of_product : 'dervie_detail_of_product',
    userInfo :[],
    myname :'',
    mobile :'',
    groupName :'',
    full_path:'',
    groupId :'',
    groupImage:'',
    profileImage:'',
    postImage:'',
    account_type:'',
    editGroup:'',
    mydeviceID :'',
    mydeviceType :'',
    event_det:'',
    event_det2:'',
    mydeviceToken :'',
    restaurantdetails : '',
    akash:'Test header',
    event_image:'',
    mymodel_name :'',
    mycarrier_name :'',
    mydevice_country :'',
    mydevice_memory :'',
    userdetails:'',
    otp:'',
    fmobile :'',
    isScreen :'',
    isScreen :'',
    type :'',
    keyword:'',
    author_id :'',
    author :'',
    another:'',
    comment_id:'',
    post_id:'',
    wallets:'',
    anotherUsername:'',
    commentFlagId:'',
    need_help:'need_help',
    COLOR: {
        ORANGE: '#C50',
        DARKBLUE: '#0F3274',
        LIGHTBLUE: '#6EA8DA',
        DARKGRAY: '#999',
    },
};
